version: '3.0'


services:
  php-nginx:
    build:
      context: .
      dockerfile: dockerfile.apache
    container_name : laravel-apache
    volumes:
      - ./:/var/www/html
    depends_on:
      - mysql
    ports:
      - "8000:80"

  mysql:
    image: mysql:latest
    ports:
      - "4306:3306"
    environment:
      MYSQL_DATABASE: docker_test
      MYSQL_USER: docker_test_user
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    restart: unless-stopped
